/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as PublicationsIndexRouteImport } from './routes/publications/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as PublicationsSlugRouteImport } from './routes/publications/$slug'
import { Route as FeedXmlRouteImport } from './routes/feed.xml'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns/$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as FeedEventsXmlRouteImport } from './routes/feed/events.xml'
import { Route as ShareSlugRouteImport } from './routes/s/$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/publications/$slug',
  path: '/publications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedXmlRoute = FeedXmlRouteImport.update({
  id: '/feed/xml',
  path: '/feed/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedEventsXmlRoute = FeedEventsXmlRouteImport.update({
  id: '/feed/events/xml',
  path: '/feed/events/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/feed/xml': typeof FeedXmlRoute
  '/feed/events/xml': typeof FeedEventsXmlRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/s/$slug': typeof ShareSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/feed/xml': typeof FeedXmlRoute
  '/feed/events/xml': typeof FeedEventsXmlRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/s/$slug': typeof ShareSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/events': typeof EventsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/feed/xml': typeof FeedXmlRoute
  '/feed/events/xml': typeof FeedEventsXmlRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/s/$slug': typeof ShareSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/privacy'
    | '/articles/$slug'
    | '/campaigns/$slug'
    | '/events/$id'
    | '/feed/xml'
    | '/feed/events/xml'
    | '/publications/$slug'
    | '/s/$slug'
    | '/wiki/$slug'
    | '/articles/'
    | '/events/'
    | '/publications/'
    | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/privacy'
    | '/articles/$slug'
    | '/campaigns/$slug'
    | '/events/$id'
    | '/feed/xml'
    | '/feed/events/xml'
    | '/publications/$slug'
    | '/s/$slug'
    | '/wiki/$slug'
    | '/articles'
    | '/events'
    | '/publications'
    | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/downloads'
    | '/privacy'
    | '/articles/$slug'
    | '/campaigns/$slug'
    | '/events/$id'
    | '/feed/xml'
    | '/feed/events/xml'
    | '/publications/$slug'
    | '/s/$slug'
    | '/wiki/$slug'
    | '/articles/'
    | '/events/'
    | '/publications/'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  DownloadsRoute: typeof DownloadsRoute
  PrivacyRoute: typeof PrivacyRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CampaignsSlugRoute: typeof CampaignsSlugRoute
  EventsIdRoute: typeof EventsIdRoute
  FeedXmlRoute: typeof FeedXmlRoute
  FeedEventsXmlRoute: typeof FeedEventsXmlRoute
  PublicationsSlugRoute: typeof PublicationsSlugRoute
  ShareSlugRoute: typeof ShareSlugRoute
  WikiSlugRoute: typeof WikiSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug': {
      id: '/publications/$slug'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/xml': {
      id: '/feed/xml'
      path: '/feed/xml'
      fullPath: '/feed/xml'
      preLoaderRoute: typeof FeedXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/events/xml': {
      id: '/feed/events/xml'
      path: '/feed/events/xml'
      fullPath: '/feed/events/xml'
      preLoaderRoute: typeof FeedEventsXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  DownloadsRoute: DownloadsRoute,
  PrivacyRoute: PrivacyRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CampaignsSlugRoute: CampaignsSlugRoute,
  EventsIdRoute: EventsIdRoute,
  FeedXmlRoute: FeedXmlRoute,
  FeedEventsXmlRoute: FeedEventsXmlRoute,
  PublicationsSlugRoute: PublicationsSlugRoute,
  ShareSlugRoute: ShareSlugRoute,
  WikiSlugRoute: WikiSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
