/**
 * Social Publishing Module Translations
 */

import { defineModuleTranslations } from '@/i18n/moduleI18n';

const socialPublishingTranslations = defineModuleTranslations({
  en: {
    'social-publishing': {
      name: 'Social Publishing',
      description: 'Schedule, share, and cross-post content across platforms',
      scheduler: {
        title: 'Schedule Content',
        scheduledFor: 'Scheduled for',
        pickDateTime: 'Pick date & time',
        timezone: 'Timezone',
        platforms: 'Platforms',
        schedule: 'Schedule',
        cancel: 'Cancel',
        recurrence: 'Repeat',
        oneTime: 'One-time',
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
      },
      share: {
        title: 'Share',
        copyLink: 'Copy Link',
        copied: 'Copied!',
        qrCode: 'QR Code',
        shareVia: 'Share via',
        password: 'Password protect',
        expiration: 'Expires',
        noExpiry: 'No expiration',
      },
      calendar: {
        title: 'Content Calendar',
        month: 'Month',
        week: 'Week',
        day: 'Day',
        noItems: 'No scheduled content',
      },
      crossPost: {
        title: 'Cross-Post',
        preview: 'Preview',
        charLimit: 'characters',
        nostr: 'Nostr',
        activitypub: 'ActivityPub (Mastodon)',
        atproto: 'AT Protocol (Bluesky)',
        rss: 'RSS Feed',
      },
      seo: {
        title: 'SEO Settings',
        metaTitle: 'Meta Title',
        metaDescription: 'Meta Description',
        ogImage: 'OG Image',
        keywords: 'Keywords',
        canonical: 'Canonical URL',
        autoGenerated: 'Auto-generated',
      },
      outreach: {
        title: 'Outreach',
        dashboard: 'Dashboard',
        totalClicks: 'Total Clicks',
        activeLinks: 'Active Links',
        scheduled: 'Scheduled',
        published: 'Published',
        failed: 'Failed',
        topLinks: 'Top Performing Links',
      },
      status: {
        pending: 'Pending',
        publishing: 'Publishing',
        published: 'Published',
        failed: 'Failed',
        cancelled: 'Cancelled',
      },
    },
  },
});

export default socialPublishingTranslations;
