//! Database schema and migration management
//!
//! Migrations are embedded at compile time from the migrations/ directory.
//! Uses rusqlite_migration for forward-only versioned migrations.
//!
//! Migration files are generated by `tools/codegen` from protocol schemas,
//! but the initial core tables migration is hand-authored since core tables
//! (identities, groups, messages, etc.) are defined in the web client's db.ts
//! rather than in protocol schemas.

use rusqlite::Connection;
use rusqlite_migration::{Migrations, M};

/// Run all pending migrations on the given connection
pub fn run_migrations(conn: &mut Connection) -> Result<(), String> {
    let migrations = Migrations::new(vec![
        // 001: Core tables (identities, groups, members, messages, etc.)
        M::up(include_str!("migrations/001_core_tables.sql")),
        // 002: Module tables (events, rsvps, proposals, wiki, etc.)
        M::up(include_str!("migrations/002_module_tables.sql")),
        // 003: Multi-device and offline support
        M::up(include_str!("migrations/003_device_offline.sql")),
    ]);

    migrations
        .to_latest(conn)
        .map_err(|e| format!("Migration error: {e}"))?;

    log::info!("Database migrations complete");
    Ok(())
}

/// Field-level encryption configuration
/// Maps table name -> list of fields that should be encrypted with NIP-44
pub fn encrypted_fields() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        ("messages", vec!["content"]),
        ("conversation_messages", vec!["content"]),
        ("conversations", vec!["name", "last_message_preview"]),
        ("events", vec!["title", "description", "location"]),
        ("groups", vec!["description"]),
        ("mutual_aid_requests", vec!["title", "description", "notes"]),
        ("proposals", vec!["title", "description"]),
        ("wiki_pages", vec!["title", "content"]),
        ("database_records", vec!["data"]),
        ("posts", vec!["content"]),
        ("friends", vec!["display_name", "notes", "username", "tags"]),
        ("friend_requests", vec!["message"]),
        ("documents", vec!["title", "content"]),
        ("files", vec!["name", "description"]),
        ("search_index", vec!["title", "content", "excerpt", "facets", "vector", "tags"]),
        ("tags", vec!["name"]),
        ("saved_searches", vec!["query", "filters"]),
        ("recent_searches", vec!["query"]),
    ]
}
