/**
 * QR Scanner Screen - Device Linking via NIP-46
 *
 * Scans a QR code from another device to establish a NIP-46 remote signing connection.
 */

import { useState, useEffect } from 'react'
import { View, Text, StyleSheet, Pressable, Alert, Platform } from 'react-native'
import { useRouter } from 'one'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { CameraView, useCameraPermissions } from 'expo-camera'
import { spacing, fontSize, fontWeight } from '@buildit/design-tokens'

interface Nip46QRData {
  bunkerUrl: string
  pubkey: string
  relay: string
  secret?: string
}

function parseNip46QR(data: string): Nip46QRData | null {
  // NIP-46 bunker URL format: bunker://<pubkey>?relay=<relay>&secret=<secret>
  // or nostrconnect://<pubkey>?relay=<relay>&secret=<secret>
  try {
    const url = new URL(data)

    if (url.protocol !== 'bunker:' && url.protocol !== 'nostrconnect:') {
      return null
    }

    const pubkey = url.hostname || url.pathname.replace('//', '')
    const relay = url.searchParams.get('relay')
    const secret = url.searchParams.get('secret') || undefined

    if (!pubkey || !relay) {
      return null
    }

    return {
      bunkerUrl: data,
      pubkey,
      relay: decodeURIComponent(relay),
      secret,
    }
  } catch {
    return null
  }
}

export default function ScanScreen() {
  const router = useRouter()
  const insets = useSafeAreaInsets()
  const [permission, requestPermission] = useCameraPermissions()
  const [scanned, setScanned] = useState(false)
  const [isProcessing, setIsProcessing] = useState(false)

  // Web doesn't support camera scanning the same way
  if (Platform.OS === 'web') {
    return (
      <View style={[styles.container, { paddingTop: insets.top }]}>
        <View style={styles.content}>
          <Text style={styles.title}>Device Linking</Text>
          <Text style={styles.subtitle}>
            Camera scanning is not supported on web.{'\n'}
            Please use a mobile device to scan QR codes.
          </Text>

          <View style={styles.webInputContainer}>
            <Text style={styles.label}>Paste bunker URL</Text>
            <Text style={styles.hint}>
              You can paste a bunker:// or nostrconnect:// URL directly
            </Text>
          </View>

          <Pressable
            style={styles.backButton}
            onPress={() => router.back()}
          >
            <Text style={styles.backButtonText}>Go Back</Text>
          </Pressable>
        </View>
      </View>
    )
  }

  if (!permission) {
    // Loading permissions
    return (
      <View style={styles.container}>
        <Text style={styles.subtitle}>Loading camera...</Text>
      </View>
    )
  }

  if (!permission.granted) {
    // Permission not granted
    return (
      <View style={[styles.container, { paddingTop: insets.top }]}>
        <View style={styles.content}>
          <Text style={styles.title}>Camera Permission</Text>
          <Text style={styles.subtitle}>
            We need camera access to scan the QR code from your other device.
          </Text>

          <Pressable style={styles.primaryButton} onPress={requestPermission}>
            <Text style={styles.primaryButtonText}>Grant Permission</Text>
          </Pressable>

          <Pressable
            style={styles.linkButton}
            onPress={() => router.back()}
          >
            <Text style={styles.linkText}>Go Back</Text>
          </Pressable>
        </View>
      </View>
    )
  }

  const handleBarCodeScanned = async ({ data }: { data: string }) => {
    if (scanned || isProcessing) return

    setScanned(true)
    setIsProcessing(true)

    const nip46Data = parseNip46QR(data)

    if (!nip46Data) {
      Alert.alert(
        'Invalid QR Code',
        'This QR code is not a valid NIP-46 device link. Please scan a QR code generated by the BuildIt web app.',
        [
          {
            text: 'Try Again',
            onPress: () => {
              setScanned(false)
              setIsProcessing(false)
            },
          },
          {
            text: 'Cancel',
            style: 'cancel',
            onPress: () => router.back(),
          },
        ]
      )
      return
    }

    // Show confirmation dialog
    Alert.alert(
      'Connect to Device?',
      `This will link your identity to:\n\nRelay: ${nip46Data.relay}\n\nThis device will be able to sign events on your behalf.`,
      [
        {
          text: 'Cancel',
          style: 'cancel',
          onPress: () => {
            setScanned(false)
            setIsProcessing(false)
          },
        },
        {
          text: 'Connect',
          onPress: async () => {
            try {
              // TODO: Implement actual NIP-46 connection
              // This would involve:
              // 1. Connecting to the relay
              // 2. Sending a connect request with the secret
              // 3. Waiting for approval from the other device
              // 4. Storing the connection details

              Alert.alert(
                'Connection Initiated',
                'Please approve the connection on your other device.',
                [
                  {
                    text: 'OK',
                    onPress: () => router.push('/'),
                  },
                ]
              )
            } catch (error) {
              Alert.alert(
                'Connection Failed',
                'Could not establish connection. Please try again.',
                [
                  {
                    text: 'OK',
                    onPress: () => {
                      setScanned(false)
                      setIsProcessing(false)
                    },
                  },
                ]
              )
            }
          },
        },
      ]
    )
  }

  return (
    <View style={styles.scanContainer}>
      <CameraView
        style={StyleSheet.absoluteFillObject}
        barcodeScannerSettings={{
          barcodeTypes: ['qr'],
        }}
        onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
      />

      {/* Overlay */}
      <View style={[styles.overlay, { paddingTop: insets.top + spacing[4] }]}>
        <Text style={styles.scanTitle}>Scan QR Code</Text>
        <Text style={styles.scanSubtitle}>
          Point your camera at the QR code shown on your other device
        </Text>
      </View>

      {/* Scan frame */}
      <View style={styles.frameContainer}>
        <View style={styles.frame}>
          <View style={[styles.corner, styles.topLeft]} />
          <View style={[styles.corner, styles.topRight]} />
          <View style={[styles.corner, styles.bottomLeft]} />
          <View style={[styles.corner, styles.bottomRight]} />
        </View>
      </View>

      {/* Back button */}
      <View style={[styles.bottomOverlay, { paddingBottom: insets.bottom + spacing[4] }]}>
        <Pressable
          style={styles.cancelButton}
          onPress={() => router.back()}
        >
          <Text style={styles.cancelButtonText}>Cancel</Text>
        </Pressable>
      </View>

      {/* Processing indicator */}
      {isProcessing && (
        <View style={styles.processingOverlay}>
          <View style={styles.processingBox}>
            <Text style={styles.processingText}>Processing...</Text>
          </View>
        </View>
      )}
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing[6],
  },
  scanContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  content: {
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
  },
  title: {
    fontSize: fontSize['2xl'],
    fontWeight: String(fontWeight.bold) as '700',
    color: '#0a0a0a',
    marginBottom: spacing[2],
    textAlign: 'center',
  },
  subtitle: {
    fontSize: fontSize.base,
    color: '#737373',
    marginBottom: spacing[8],
    textAlign: 'center',
    lineHeight: 22,
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#0a0a0a',
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[6],
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  primaryButtonText: {
    color: '#fafafa',
    fontSize: fontSize.base,
    fontWeight: String(fontWeight.semibold) as '600',
  },
  linkButton: {
    padding: spacing[2],
  },
  linkText: {
    color: '#0a0a0a',
    fontSize: fontSize.sm,
  },
  webInputContainer: {
    width: '100%',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: spacing[4],
    marginBottom: spacing[6],
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: String(fontWeight.medium) as '500',
    color: '#0a0a0a',
    marginBottom: spacing[1],
  },
  hint: {
    fontSize: fontSize.xs,
    color: '#737373',
  },
  backButton: {
    width: '100%',
    backgroundColor: '#0a0a0a',
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[6],
    borderRadius: 12,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#fafafa',
    fontSize: fontSize.base,
    fontWeight: String(fontWeight.semibold) as '600',
  },
  // Scanner styles
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    padding: spacing[6],
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
  },
  scanTitle: {
    fontSize: fontSize.xl,
    fontWeight: String(fontWeight.bold) as '700',
    color: '#ffffff',
    marginBottom: spacing[2],
  },
  scanSubtitle: {
    fontSize: fontSize.sm,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
  },
  frameContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  frame: {
    width: 250,
    height: 250,
    position: 'relative',
  },
  corner: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderColor: '#ffffff',
    borderWidth: 3,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  topRight: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  bottomOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: spacing[6],
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[8],
    borderRadius: 24,
  },
  cancelButtonText: {
    color: '#ffffff',
    fontSize: fontSize.base,
    fontWeight: String(fontWeight.medium) as '500',
  },
  processingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingBox: {
    backgroundColor: '#ffffff',
    paddingVertical: spacing[4],
    paddingHorizontal: spacing[6],
    borderRadius: 12,
  },
  processingText: {
    fontSize: fontSize.base,
    color: '#0a0a0a',
  },
})
