/**
 * SEOEditor Component
 *
 * Inline editor for meta title, description, OG image preview,
 * keywords, and canonical URL. Shows a live preview of how the
 * content will appear in search results and social cards.
 *
 * OG images are auto-generated by the self-hosted API worker —
 * no external services.
 */

import { FC, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import {
  Search,
  Image as ImageIcon,
  Tag,
  X,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { SEOOverrides } from '../types';

interface SEOEditorProps {
  /** Current SEO overrides */
  value: Partial<SEOOverrides>;
  /** Called when SEO fields change */
  onChange: (value: Partial<SEOOverrides>) => void;
  /** Type of content (for auto-generated OG image) */
  contentType?: 'article' | 'event' | 'listing' | 'campaign' | 'profile' | 'default';
  /** Title of the content (used for auto-generation) */
  contentTitle?: string;
  /** Canonical base URL */
  baseUrl?: string;
  className?: string;
}

const META_TITLE_LIMIT = 60;
const META_DESC_LIMIT = 160;

export const SEOEditor: FC<SEOEditorProps> = ({
  value,
  onChange,
  contentType = 'default',
  contentTitle = '',
  baseUrl = 'https://buildit.network',
  className,
}) => {
  const { t } = useTranslation();
  const [newKeyword, setNewKeyword] = useState('');

  const title = value.title || contentTitle;
  const description = value.description || '';
  const keywords = value.keywords || [];

  const ogImageUrl =
    value.ogImageUrl ||
    `https://api.buildit.network/api/og-image?type=${contentType}&title=${encodeURIComponent(contentTitle)}`;

  const update = (updates: Partial<SEOOverrides>) => {
    onChange({ ...value, ...updates });
  };

  const addKeyword = () => {
    const trimmed = newKeyword.trim().toLowerCase();
    if (trimmed && !keywords.includes(trimmed)) {
      update({ keywords: [...keywords, trimmed] });
      setNewKeyword('');
    }
  };

  const removeKeyword = (keyword: string) => {
    update({ keywords: keywords.filter((k) => k !== keyword) });
  };

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Search className="h-5 w-5" />
          {t('social-publishing.seo.title')}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-5">
        {/* Meta Title */}
        <div className="space-y-2">
          <Label className="text-sm">{t('social-publishing.seo.metaTitle')}</Label>
          <Input
            value={value.title || ''}
            onChange={(e) => update({ title: e.target.value })}
            placeholder={contentTitle || 'Page title'}
            maxLength={70}
          />
          <p className={`text-xs ${
            title.length > META_TITLE_LIMIT ? 'text-destructive' : 'text-muted-foreground'
          }`}>
            {title.length}/{META_TITLE_LIMIT} characters
          </p>
        </div>

        {/* Meta Description */}
        <div className="space-y-2">
          <Label className="text-sm">{t('social-publishing.seo.metaDescription')}</Label>
          <Textarea
            value={value.description || ''}
            onChange={(e) => update({ description: e.target.value })}
            placeholder="Brief description for search engines..."
            rows={3}
            maxLength={200}
          />
          <p className={`text-xs ${
            description.length > META_DESC_LIMIT ? 'text-destructive' : 'text-muted-foreground'
          }`}>
            {description.length}/{META_DESC_LIMIT} characters
          </p>
        </div>

        {/* OG Image */}
        <div className="space-y-2">
          <Label className="text-sm flex items-center gap-2">
            <ImageIcon className="h-4 w-4" />
            {t('social-publishing.seo.ogImage')}
          </Label>
          <Input
            value={value.ogImageUrl || ''}
            onChange={(e) => update({ ogImageUrl: e.target.value })}
            placeholder={t('social-publishing.seo.autoGenerated')}
          />
          {/* OG Image Preview */}
          <div className="border rounded-lg overflow-hidden bg-muted">
            <img
              src={ogImageUrl}
              alt="OG Image Preview"
              className="w-full h-auto max-h-48 object-cover"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = 'none';
              }}
            />
          </div>
          <p className="text-xs text-muted-foreground">
            {value.ogImageUrl
              ? 'Custom image'
              : `${t('social-publishing.seo.autoGenerated')} — self-hosted, no external services`}
          </p>
        </div>

        {/* Keywords */}
        <div className="space-y-2">
          <Label className="text-sm flex items-center gap-2">
            <Tag className="h-4 w-4" />
            {t('social-publishing.seo.keywords')}
          </Label>
          <div className="flex gap-2">
            <Input
              value={newKeyword}
              onChange={(e) => setNewKeyword(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  addKeyword();
                }
              }}
              placeholder="Add keyword..."
              className="text-sm"
            />
            <Button size="sm" variant="outline" onClick={addKeyword}>
              Add
            </Button>
          </div>
          {keywords.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {keywords.map((keyword) => (
                <Badge key={keyword} variant="secondary" className="text-xs gap-1">
                  {keyword}
                  <button
                    onClick={() => removeKeyword(keyword)}
                    className="ml-1 hover:text-destructive"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
            </div>
          )}
        </div>

        <Separator />

        {/* Search Preview */}
        <div className="space-y-2">
          <Label className="text-sm text-muted-foreground">Search result preview</Label>
          <div className="border rounded-lg p-3 bg-white dark:bg-zinc-950 space-y-1">
            <p className="text-xs text-green-700 dark:text-green-400 truncate">
              {baseUrl}/{contentType}/{contentTitle.toLowerCase().replace(/\s+/g, '-')}
            </p>
            <p className="text-blue-700 dark:text-blue-400 font-medium truncate">
              {title || 'Page Title'} — BuildIt Network
            </p>
            <p className="text-xs text-muted-foreground line-clamp-2">
              {description || 'No description set. Search engines may generate their own snippet.'}
            </p>
          </div>
        </div>

        {/* Social Card Preview */}
        <div className="space-y-2">
          <Label className="text-sm text-muted-foreground">Social card preview</Label>
          <div className="border rounded-lg overflow-hidden bg-white dark:bg-zinc-950">
            <div className="h-32 bg-muted flex items-center justify-center">
              <img
                src={ogImageUrl}
                alt=""
                className="w-full h-full object-cover"
                onError={(e) => {
                  (e.target as HTMLImageElement).style.display = 'none';
                }}
              />
            </div>
            <div className="p-3 space-y-1">
              <p className="text-xs text-muted-foreground">buildit.network</p>
              <p className="font-medium text-sm truncate">
                {title || 'Page Title'}
              </p>
              <p className="text-xs text-muted-foreground line-clamp-2">
                {description || 'Description will appear here.'}
              </p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
