/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Modules

const IndexLazyImport = createFileRoute('/')()
const WikiIndexLazyImport = createFileRoute('/wiki/')()
const WikiSlugLazyImport = createFileRoute('/wiki/$slug')()
const ArticlesIndexLazyImport = createFileRoute('/articles/')()
const ArticlesSlugLazyImport = createFileRoute('/articles/$slug')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as unknown as Parameters<typeof IndexLazyImport.update>[0])

const WikiIndexLazyRoute = WikiIndexLazyImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRoute,
} as unknown as Parameters<typeof WikiIndexLazyImport.update>[0])

const WikiSlugLazyRoute = WikiSlugLazyImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRoute,
} as unknown as Parameters<typeof WikiSlugLazyImport.update>[0])

const ArticlesIndexLazyRoute = ArticlesIndexLazyImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRoute,
} as unknown as Parameters<typeof ArticlesIndexLazyImport.update>[0])

const ArticlesSlugLazyRoute = ArticlesSlugLazyImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRoute,
} as unknown as Parameters<typeof ArticlesSlugLazyImport.update>[0])

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugLazyImport
      parentRoute: typeof rootRoute
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/articles': typeof ArticlesIndexLazyRoute
  '/articles/$slug': typeof ArticlesSlugLazyRoute
  '/wiki': typeof WikiIndexLazyRoute
  '/wiki/$slug': typeof WikiSlugLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/articles': typeof ArticlesIndexLazyRoute
  '/articles/$slug': typeof ArticlesSlugLazyRoute
  '/wiki': typeof WikiIndexLazyRoute
  '/wiki/$slug': typeof WikiSlugLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/articles/': typeof ArticlesIndexLazyRoute
  '/articles/$slug': typeof ArticlesSlugLazyRoute
  '/wiki/': typeof WikiIndexLazyRoute
  '/wiki/$slug': typeof WikiSlugLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles' | '/articles/$slug' | '/wiki' | '/wiki/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles' | '/articles/$slug' | '/wiki' | '/wiki/$slug'
  id: '__root__' | '/' | '/articles/' | '/articles/$slug' | '/wiki/' | '/wiki/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ArticlesIndexLazyRoute: typeof ArticlesIndexLazyRoute
  ArticlesSlugLazyRoute: typeof ArticlesSlugLazyRoute
  WikiIndexLazyRoute: typeof WikiIndexLazyRoute
  WikiSlugLazyRoute: typeof WikiSlugLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ArticlesIndexLazyRoute: ArticlesIndexLazyRoute,
  ArticlesSlugLazyRoute: ArticlesSlugLazyRoute,
  WikiIndexLazyRoute: WikiIndexLazyRoute,
  WikiSlugLazyRoute: WikiSlugLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/articles/",
        "/articles/$slug",
        "/wiki/",
        "/wiki/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/articles/": {
      "filePath": "articles/index.tsx"
    },
    "/articles/$slug": {
      "filePath": "articles/$slug.tsx"
    },
    "/wiki/": {
      "filePath": "wiki/index.tsx"
    },
    "/wiki/$slug": {
      "filePath": "wiki/$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
