/**
 * Tauri E2E Test Utilities
 *
 * Centralized exports for all Tauri testing utilities.
 */

// Tauri mock functions
export {
  initializeTauriMocks,
  setupTauriMocks,
  clearTauriMocks,
  getTauriMockState,
  simulateBleDeviceDiscovery,
  simulateBleConnectionChange,
  simulateBleMessage,
  type DiscoveredDevice,
  type BleStatus,
  type CommandResult,
  type KeyPairResponse,
  type SecretType,
  type TauriMockState,
} from './tauri-mocks';

// Test fixtures
export {
  TEST_KEYPAIR,
  TEST_KEYPAIR_ALT,
  TEST_NSEC,
  TEST_NPUB,
  MOCK_BUILDIT_DEVICE,
  MOCK_BUILDIT_DEVICE_2,
  MOCK_OTHER_DEVICE,
  MOCK_UNNAMED_DEVICE,
  MOCK_DEVICES_LIST,
  MOCK_TEXT_MESSAGE,
  MOCK_ENCRYPTED_MESSAGE,
  MOCK_MESH_HEADER,
  MOCK_KEYRING_SECRETS,
  TEST_USERS,
  DEFAULT_WINDOW_CONFIG,
  TIMEOUTS,
  SELECTORS,
  type TestUserProfile,
} from './fixtures';

// Test helpers
export {
  initializeTauriPage,
  waitForAppReady,
  clearStorageAndReload,
  createIdentity,
  importIdentity,
  loginAsTestUser,
  logout,
  navigateTo,
  navigateToSettings,
  navigateToSecuritySettings,
  waitForBlePanel,
  startBleScan,
  stopBleScan,
  getDiscoveredDevices,
  connectToDevice,
  sendMessage,
  getMessages,
  assertLoggedIn,
  assertOnLoginPage,
  assertBleScanning,
  assertDeviceConnected,
  takeScreenshot,
  logPageState,
  waitForCondition,
  waitForToast,
} from './helpers';

// Crypto test vectors
export {
  ALICE_KEYPAIR,
  BOB_KEYPAIR,
  CHARLIE_KEYPAIR,
  RANDOM_KEYPAIR_1,
  RANDOM_KEYPAIR_2,
  KEY_PATTERNS,
  INVALID_KEY_VECTORS,
  NIP44_TEST_VECTORS,
  TEST_MESSAGES,
  SECRET_TYPES,
  TEST_SECRETS,
  isValidHex,
  isValidBase64,
  randomHex,
  stringToHex,
  hexToString,
  TEST_USERS as CRYPTO_TEST_USERS,
  type KeyPair,
  type TestVector,
  type ConversationKeyVector,
} from './crypto-test-vectors';

// Mock BLE responses
export {
  BUILDIT_NODE_PRIMARY,
  BUILDIT_NODE_SECONDARY,
  BUILDIT_NODE_RELAY,
  BUILDIT_NODE_EDGE,
  GENERIC_HEADPHONES,
  GENERIC_FITNESS_TRACKER,
  UNNAMED_DEVICE,
  WEAK_SIGNAL_DEVICE,
  BUILDIT_DEVICES,
  GENERIC_DEVICES,
  ALL_DEVICES,
  STRONG_SIGNAL_DEVICES,
  CONNECTABLE_BUILDIT_DEVICES,
  GRADUAL_DISCOVERY_SCENARIO,
  FLUCTUATING_DEVICES_SCENARIO,
  EMPTY_SCAN_SCENARIO,
  CROWDED_SCAN_SCENARIO,
  INITIAL_BLE_STATUS,
  SCANNING_BLE_STATUS,
  SCANNING_WITH_DEVICES_STATUS,
  CONNECTED_ONE_DEVICE_STATUS,
  MESH_NETWORK_ACTIVE_STATUS,
  TEXT_MESSAGE_PAYLOAD,
  ENCRYPTED_MESSAGE_PAYLOAD,
  MESH_HEADER,
  FULL_MESH_MESSAGE,
  PING_MESSAGE,
  PONG_MESSAGE,
  HEARTBEAT_MESSAGE,
  CONNECTION_ERRORS,
  SCAN_ERRORS,
  MESSAGE_ERRORS,
  createMockDevice,
  createMockBuilditNodes,
  fluctuateRssi,
  createMeshMessage,
  parseMeshMessage,
  type ConnectionError,
  type ScanError,
  type MessageError,
} from './mock-ble-responses';
